#!/usr/bin/env python3
"""Agentic Controller Trajectory Synthesis pipeline.

Workflow:
1) Generate non-oracle action_search_prompt from query.
2) Run Nuva agent backend (Agno-driven) OR use provided run artifacts.
3) Critique and score trajectory against gold agent.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import uuid
from dataclasses import asdict, dataclass
from typing import Any
from urllib import error, request

DEFAULT_MODEL = "gpt-5.4-nano"
DEFAULT_NUVA_AGENT_ID = "Nuva_v1"
DEFAULT_NUVA_API_BASE = "https://api.example.com"
DEFAULT_NUVA_WEB_URL = "https://os.agno.com/chat?type=agent&id=Nuva_v1"

ACTION_SEARCH_SYSTEM_PROMPT = """You are helping construct search guidance for an agentic agent-generation controller.

Given a user task query, generate a concise but high-recall search prompt that helps the controller retrieve useful LLM and tool candidates for solving the task.

Requirements:
1. Do NOT generate the final agent.
2. Do NOT mention any gold backbone, gold tool name, or label.
3. Focus on the capabilities needed to solve the task.
4. Include domain concepts, reasoning requirements, and possible tool capabilities.
5. Prefer search-oriented wording that can help retrieve relevant candidates.
6. Avoid overly narrow wording that simply restates one possible answer.
7. Output only JSON.

Return format:
{
  "action_search_prompt": "...",
  "capability_keywords": ["...", "...", "..."],
  "reasoning_type": "...",
  "expected_evidence": "..."
}
"""

CRITIQUE_SYSTEM_PROMPT = """You are an evaluator for agent-generation trajectories.

You will be given:
1. A user task query.
2. A gold agent label, including the target backbone and target tools.
3. The action_search_prompt used to guide the controller.
4. The run session history.
5. The final response_result generated by the system.

Your task is to evaluate the quality of the generated agent.

Important:
- The gold agent is used only for evaluation.
- Do not rewrite the final agent.
- Do not reward exact string overlap alone.
- Focus on functional equivalence, capability coverage, and whether the generated agent can solve the user task.

Definitions:

match_score evaluates how well the response_result matches the gold_agent:
1 = clear mismatch: almost unrelated to the gold agent.
2 = weak mismatch: only superficial overlap; key gold capabilities are missing.
3 = borderline mismatch: partial overlap, but important backbone/tool capabilities are missing or wrong.
4 = borderline match: main intent is covered, but there are noticeable omissions, noise, or imprecise tool choices.
5 = clear match: highly consistent with the gold agent; only minor differences.
6 = strong match: functionally equivalent or better; backbone and tools strongly align with the gold label.

capability_score evaluates whether the response_result itself can solve the task query:
1 = unusable: invalid or irrelevant agent.
2 = poor capability: weakly related but lacks core capabilities.
3 = borderline capable: may partially solve the task but is incomplete or unreliable.
4 = moderately capable: can solve most of the task, with some imperfections.
5 = clearly capable: well-suited to the task with appropriate capabilities.
6 = highly capable: very strong task alignment, complete capability coverage, and reliable profile/policy.

Return only JSON with the following fields:
{
  "match_score": int,
  "capability_score": int,
  "match_rationale": "...",
  "capability_rationale": "...",
  "missing_capabilities": ["...", "..."],
  "noisy_or_irrelevant_components": ["...", "..."],
  "keep_for_sft": true/false,
  "quality_tag": "strong_positive | positive | borderline | negative"
}
"""


@dataclass
class GoldAgent:
    backbone: str
    tools: list[str]


@dataclass
class RunArtifacts:
    session_id: str
    session_history: list[dict[str, Any]]
    response_result: dict[str, Any]
    raw_backend_response: dict[str, Any] | None = None


@dataclass
class Evaluation:
    match_score: int
    capability_score: int
    match_rationale: str
    capability_rationale: str
    missing_capabilities: list[str]
    noisy_or_irrelevant_components: list[str]
    keep_for_sft: bool
    quality_tag: str


@dataclass
class SampleRecord:
    id: str
    query: str
    gold_agent: GoldAgent
    action_search_prompt: str
    capability_keywords: list[str]
    reasoning_type: str
    expected_evidence: str
    run: RunArtifacts
    evaluation: Evaluation


class OpenAIResponsesClient:
    def __init__(self, model: str = DEFAULT_MODEL, api_key: str | None = None) -> None:
        self.model = model
        self.api_key = api_key or os.getenv("OPENAI_API_KEY")
        if not self.api_key:
            raise ValueError("OPENAI_API_KEY is required unless --mock is used.")

    def json_completion(self, system_prompt: str, user_payload: dict[str, Any]) -> dict[str, Any]:
        payload = {
            "model": self.model,
            "input": [
                {"role": "system", "content": [{"type": "input_text", "text": system_prompt}]},
                {"role": "user", "content": [{"type": "input_text", "text": json.dumps(user_payload, ensure_ascii=False)}]},
            ],
            "text": {"format": {"type": "json_object"}},
        }
        req = request.Request(
            "https://api.openai.com/v1/responses",
            data=json.dumps(payload).encode("utf-8"),
            headers={"Authorization": f"Bearer {self.api_key}", "Content-Type": "application/json"},
            method="POST",
        )
        try:
            with request.urlopen(req, timeout=120) as resp:
                body = json.loads(resp.read().decode("utf-8"))
        except error.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="ignore")
            raise RuntimeError(f"OpenAI API error: {exc.code} {detail}") from exc

        return safe_json_loads(body.get("output_text", ""))


class NuvaAgentClient:
    """HTTP client for Agno-driven Nuva agent run endpoint.

    Equivalent to the user-provided curl:
    POST /agents/{agent_id}/runs with multipart/form-data fields.
    """

    def __init__(self, api_base: str, token: str, agent_id: str) -> None:
        self.api_base = api_base.rstrip("/")
        self.token = token
        self.agent_id = agent_id

    def run(
        self,
        *,
        message: str,
        session_id: str,
        user_id: str,
        stream: bool = True,
        files: str = "",
        version: str = "",
        background: bool = False,
    ) -> dict[str, Any]:
        url = f"{self.api_base}/agents/{self.agent_id}/runs"
        fields = {
            "message": message,
            "stream": str(stream).lower(),
            "session_id": session_id,
            "user_id": user_id,
            "files": files,
            "version": version,
            "background": str(background).lower(),
        }
        content_type, body = encode_multipart_form_data(fields)
        req = request.Request(
            url,
            data=body,
            headers={
                "Authorization": f"Bearer {self.token}",
                "Content-Type": content_type,
            },
            method="POST",
        )
        try:
            with request.urlopen(req, timeout=180) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except error.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="ignore")
            raise RuntimeError(f"Nuva API error: {exc.code} {detail}") from exc


class MockClient:
    def json_completion(self, system_prompt: str, user_payload: dict[str, Any]) -> dict[str, Any]:
        if "search guidance" in system_prompt:
            query = user_payload["query"]
            return {
                "action_search_prompt": f"Search candidates and tools to solve: {query[:120]}",
                "capability_keywords": ["retrieval", "reasoning", "planning"],
                "reasoning_type": "task-grounded reasoning",
                "expected_evidence": "Evidence should include domain-specific capability coverage.",
            }
        return {
            "match_score": 4,
            "capability_score": 5,
            "match_rationale": "Mock: major intentions overlap.",
            "capability_rationale": "Mock: output can likely solve query.",
            "missing_capabilities": [],
            "noisy_or_irrelevant_components": [],
            "keep_for_sft": True,
            "quality_tag": "positive",
        }


class MockNuvaAgentClient:
    def run(self, **kwargs: Any) -> dict[str, Any]:
        message = kwargs["message"]
        return {
            "session_id": kwargs["session_id"],
            "session_history": [
                {"step": 1, "action": "SearchLLM", "argument": message, "observation": "Mock llm candidates"},
                {"step": 2, "action": "SearchTool", "argument": message, "observation": "Mock tool candidates"},
                {"step": 3, "action": "Generate", "argument": message, "observation": "Mock generated agent"},
            ],
            "response_result": {
                "backbone": "openai__gpt-4.1",
                "tools": ["immunology_literature_search", "biomarker_reasoning_tool"],
                "profile": "Biomedical reasoning agent",
                "policy": "retrieve -> reason -> synthesize",
            },
        }


def safe_json_loads(text: str) -> dict[str, Any]:
    try:
        parsed = json.loads(text)
        if not isinstance(parsed, dict):
            raise ValueError("Top-level response is not object JSON")
        return parsed
    except json.JSONDecodeError:
        return json.loads(extract_first_json_object(text))


def extract_first_json_object(text: str) -> str:
    match = re.search(r"\{.*\}", text, flags=re.DOTALL)
    if not match:
        raise ValueError("Could not find JSON object in model output")
    return match.group(0)


def encode_multipart_form_data(fields: dict[str, str]) -> tuple[str, bytes]:
    boundary = f"----NuvaBoundary{uuid.uuid4().hex}"
    lines: list[bytes] = []
    for name, value in fields.items():
        lines.extend(
            [
                f"--{boundary}".encode("utf-8"),
                f'Content-Disposition: form-data; name="{name}"'.encode("utf-8"),
                b"",
                str(value).encode("utf-8"),
            ]
        )
    lines.append(f"--{boundary}--".encode("utf-8"))
    lines.append(b"")
    body = b"\r\n".join(lines)
    return f"multipart/form-data; boundary={boundary}", body


def quality_tag(match_score: int, capability_score: int) -> str:
    if match_score >= 5 and capability_score >= 5:
        return "strong_positive"
    if match_score >= 4 and capability_score >= 4:
        return "positive"
    if match_score >= 3 and capability_score >= 3:
        return "borderline"
    return "negative"


def keep_for_sft(match_score: int, capability_score: int) -> bool:
    return match_score >= 4 and capability_score >= 4


def generate_action_search(client: Any, query: str) -> dict[str, Any]:
    payload = {
        "query": query,
        "instruction": "Generate a search-oriented action prompt for an agentic controller.",
    }
    result = client.json_completion(ACTION_SEARCH_SYSTEM_PROMPT, payload)
    required = ["action_search_prompt", "capability_keywords", "reasoning_type", "expected_evidence"]
    missing = [k for k in required if k not in result]
    if missing:
        raise ValueError(f"Action search output missing keys: {missing}")
    return result


def evaluate_trajectory(
    client: Any,
    query: str,
    gold_agent: dict[str, Any],
    action_search_prompt: str,
    session_history: list[dict[str, Any]],
    response_result: dict[str, Any],
) -> dict[str, Any]:
    payload = {
        "query": query,
        "gold_agent": gold_agent,
        "action_search_prompt": action_search_prompt,
        "session_history": session_history,
        "response_result": response_result,
    }
    result = client.json_completion(CRITIQUE_SYSTEM_PROMPT, payload)
    ms = max(1, min(6, int(result["match_score"])))
    cs = max(1, min(6, int(result["capability_score"])))
    result["match_score"] = ms
    result["capability_score"] = cs
    result["quality_tag"] = quality_tag(ms, cs)
    result["keep_for_sft"] = keep_for_sft(ms, cs)
    result.setdefault("match_rationale", "")
    result.setdefault("capability_rationale", "")
    result.setdefault("missing_capabilities", [])
    result.setdefault("noisy_or_irrelevant_components", [])
    return result


def extract_run_artifacts(nuva_response: dict[str, Any], fallback_session_id: str) -> RunArtifacts:
    """Normalize backend response shape.

    Supports either direct keys:
      - session_history, response_result
    or nested run object:
      - run.session_history, run.response_result
    """
    run_obj = nuva_response.get("run", nuva_response)
    session_history = run_obj.get("session_history") or []
    response_result = run_obj.get("response_result") or run_obj.get("response") or {}
    session_id = run_obj.get("session_id") or nuva_response.get("session_id") or fallback_session_id

    if not isinstance(session_history, list):
        raise ValueError("session_history must be a list in Nuva response")
    if not isinstance(response_result, dict):
        raise ValueError("response_result must be an object in Nuva response")
    return RunArtifacts(
        session_id=session_id,
        session_history=session_history,
        response_result=response_result,
        raw_backend_response=nuva_response,
    )


def run_nuva_if_needed(input_payload: dict[str, Any], action_search_prompt: str, args: argparse.Namespace) -> RunArtifacts:
    if "run" in input_payload:
        run = input_payload["run"]
        return RunArtifacts(
            session_id=run["session_id"],
            session_history=run["session_history"],
            response_result=run["response_result"],
            raw_backend_response=None,
        )

    session_id = args.session_id or f"nuva_{uuid.uuid4().hex[:12]}"
    user_id = args.user_id or "trajectory_synth_user"
    message = f"query:\n{input_payload['query']}\n\naction_search_prompt:\n{action_search_prompt}"

    if args.mock:
        nuva_client: Any = MockNuvaAgentClient()
    else:
        token = args.nuva_token or os.getenv("NUVA_API_TOKEN")
        if not token:
            raise ValueError("NUVA_API_TOKEN (or --nuva-token) is required when run is not pre-provided.")
        nuva_client = NuvaAgentClient(api_base=args.nuva_api_base, token=token, agent_id=args.nuva_agent_id)

    nuva_resp = nuva_client.run(
        message=message,
        stream=True,
        session_id=session_id,
        user_id=user_id,
        files=args.files,
        version=args.version,
        background=False,
    )
    return extract_run_artifacts(nuva_resp, fallback_session_id=session_id)


def build_record(input_payload: dict[str, Any], llm_client: Any, args: argparse.Namespace) -> SampleRecord:
    action = generate_action_search(llm_client, input_payload["query"])
    run = run_nuva_if_needed(input_payload, action["action_search_prompt"], args)

    eval_result = evaluate_trajectory(
        client=llm_client,
        query=input_payload["query"],
        gold_agent=input_payload["gold_agent"],
        action_search_prompt=action["action_search_prompt"],
        session_history=run.session_history,
        response_result=run.response_result,
    )

    return SampleRecord(
        id=input_payload["id"],
        query=input_payload["query"],
        gold_agent=GoldAgent(**input_payload["gold_agent"]),
        action_search_prompt=action["action_search_prompt"],
        capability_keywords=action["capability_keywords"],
        reasoning_type=action["reasoning_type"],
        expected_evidence=action["expected_evidence"],
        run=run,
        evaluation=Evaluation(**eval_result),
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Synthesize and evaluate agentic trajectories.")
    parser.add_argument("--input", required=True, help="Input JSON path with id/query/gold_agent and optional run")
    parser.add_argument("--output", required=True, help="Output JSON path")
    parser.add_argument("--model", default=DEFAULT_MODEL, help="OpenAI model for prompt+critique")
    parser.add_argument("--mock", action="store_true", help="Use mock model and mock Nuva backend")

    # Nuva/Agno settings (used only when input does not already contain run)
    parser.add_argument("--nuva-api-base", default=DEFAULT_NUVA_API_BASE, help="Nuva API base URL")
    parser.add_argument("--nuva-agent-id", default=DEFAULT_NUVA_AGENT_ID, help="Nuva agent id (e.g. Nuva_v1)")
    parser.add_argument("--nuva-token", default=None, help="Nuva API bearer token; fallback env NUVA_API_TOKEN")
    parser.add_argument("--session-id", default=None, help="Optional Nuva session id")
    parser.add_argument("--user-id", default=None, help="Optional Nuva user id")
    parser.add_argument("--files", default="", help="Nuva files form-field content")
    parser.add_argument("--version", default="", help="Nuva version form-field content")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    with open(args.input, "r", encoding="utf-8") as f:
        payload = json.load(f)

    llm_client = MockClient() if args.mock else OpenAIResponsesClient(model=args.model)
    record = build_record(payload, llm_client, args)

    with open(args.output, "w", encoding="utf-8") as f:
        json.dump(asdict(record), f, ensure_ascii=False, indent=2)
        f.write("\n")

    print(f"Wrote synthesized sample to {args.output}")
    if payload.get("run") is None:
        print(f"Nuva endpoint pattern: {args.nuva_api_base}/agents/{args.nuva_agent_id}/runs")
        print(f"Nuva web reference: {DEFAULT_NUVA_WEB_URL}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
