#!/usr/bin/env python3
"""Agentic Controller Trajectory Synthesis pipeline.

Implements a 3-stage workflow:
1) Generate non-oracle action_search_prompt from query.
2) Attach run artifacts (session history + response result) from controller backend.
3) Critique and score trajectory against gold agent.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from dataclasses import asdict, dataclass
from typing import Any
from urllib import error, request

DEFAULT_MODEL = "gpt-5.4-nano"

ACTION_SEARCH_SYSTEM_PROMPT = """You are helping construct search guidance for an agentic agent-generation controller.

Given a user task query, generate a concise but high-recall search prompt that helps the controller retrieve useful LLM and tool candidates for solving the task.

Requirements:
1. Do NOT generate the final agent.
2. Do NOT mention any gold backbone, gold tool name, or label.
3. Focus on the capabilities needed to solve the task.
4. Include domain concepts, reasoning requirements, and possible tool capabilities.
5. Prefer search-oriented wording that can help retrieve relevant candidates.
6. Avoid overly narrow wording that simply restates one possible answer.
7. Output only JSON.

Return format:
{
  "action_search_prompt": "...",
  "capability_keywords": ["...", "...", "..."],
  "reasoning_type": "...",
  "expected_evidence": "..."
}
"""

CRITIQUE_SYSTEM_PROMPT = """You are an evaluator for agent-generation trajectories.

You will be given:
1. A user task query.
2. A gold agent label, including the target backbone and target tools.
3. The action_search_prompt used to guide the controller.
4. The run session history.
5. The final response_result generated by the system.

Your task is to evaluate the quality of the generated agent.

Important:
- The gold agent is used only for evaluation.
- Do not rewrite the final agent.
- Do not reward exact string overlap alone.
- Focus on functional equivalence, capability coverage, and whether the generated agent can solve the user task.

Definitions:

match_score evaluates how well the response_result matches the gold_agent:
1 = clear mismatch: almost unrelated to the gold agent.
2 = weak mismatch: only superficial overlap; key gold capabilities are missing.
3 = borderline mismatch: partial overlap, but important backbone/tool capabilities are missing or wrong.
4 = borderline match: main intent is covered, but there are noticeable omissions, noise, or imprecise tool choices.
5 = clear match: highly consistent with the gold agent; only minor differences.
6 = strong match: functionally equivalent or better; backbone and tools strongly align with the gold label.

capability_score evaluates whether the response_result itself can solve the task query:
1 = unusable: invalid or irrelevant agent.
2 = poor capability: weakly related but lacks core capabilities.
3 = borderline capable: may partially solve the task but is incomplete or unreliable.
4 = moderately capable: can solve most of the task, with some imperfections.
5 = clearly capable: well-suited to the task with appropriate capabilities.
6 = highly capable: very strong task alignment, complete capability coverage, and reliable profile/policy.

Return only JSON with the following fields:
{
  "match_score": int,
  "capability_score": int,
  "match_rationale": "...",
  "capability_rationale": "...",
  "missing_capabilities": ["...", "..."],
  "noisy_or_irrelevant_components": ["...", "..."],
  "keep_for_sft": true/false,
  "quality_tag": "strong_positive | positive | borderline | negative"
}
"""


@dataclass
class GoldAgent:
    backbone: str
    tools: list[str]


@dataclass
class RunArtifacts:
    session_id: str
    session_history: list[dict[str, Any]]
    response_result: dict[str, Any]


@dataclass
class Evaluation:
    match_score: int
    capability_score: int
    match_rationale: str
    capability_rationale: str
    missing_capabilities: list[str]
    noisy_or_irrelevant_components: list[str]
    keep_for_sft: bool
    quality_tag: str


@dataclass
class SampleRecord:
    id: str
    query: str
    gold_agent: GoldAgent
    action_search_prompt: str
    capability_keywords: list[str]
    reasoning_type: str
    expected_evidence: str
    run: RunArtifacts
    evaluation: Evaluation


class OpenAIResponsesClient:
    """Tiny REST client (no external dependency)."""

    def __init__(self, model: str = DEFAULT_MODEL, api_key: str | None = None) -> None:
        self.model = model
        self.api_key = api_key or os.getenv("OPENAI_API_KEY")
        if not self.api_key:
            raise ValueError("OPENAI_API_KEY is required unless --mock is used.")

    def json_completion(self, system_prompt: str, user_payload: dict[str, Any]) -> dict[str, Any]:
        payload = {
            "model": self.model,
            "input": [
                {"role": "system", "content": [{"type": "input_text", "text": system_prompt}]},
                {
                    "role": "user",
                    "content": [{"type": "input_text", "text": json.dumps(user_payload, ensure_ascii=False)}],
                },
            ],
            "text": {"format": {"type": "json_object"}},
        }
        req = request.Request(
            "https://api.openai.com/v1/responses",
            data=json.dumps(payload).encode("utf-8"),
            headers={
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json",
            },
            method="POST",
        )
        try:
            with request.urlopen(req, timeout=120) as resp:
                body = json.loads(resp.read().decode("utf-8"))
        except error.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="ignore")
            raise RuntimeError(f"OpenAI API error: {exc.code} {detail}") from exc

        text = body.get("output_text", "")
        return safe_json_loads(text)


class MockClient:
    def json_completion(self, system_prompt: str, user_payload: dict[str, Any]) -> dict[str, Any]:
        if "search guidance" in system_prompt:
            query = user_payload["query"]
            return {
                "action_search_prompt": f"Search candidates and tools to solve: {query[:120]}",
                "capability_keywords": ["retrieval", "reasoning", "planning"],
                "reasoning_type": "task-grounded reasoning",
                "expected_evidence": "Evidence should include domain-specific capability coverage.",
            }
        return {
            "match_score": 4,
            "capability_score": 5,
            "match_rationale": "Mock: major intentions overlap.",
            "capability_rationale": "Mock: output can likely solve query.",
            "missing_capabilities": [],
            "noisy_or_irrelevant_components": [],
            "keep_for_sft": True,
            "quality_tag": "positive",
        }


def safe_json_loads(text: str) -> dict[str, Any]:
    try:
        obj = json.loads(text)
        if not isinstance(obj, dict):
            raise ValueError("Top-level response is not a JSON object.")
        return obj
    except json.JSONDecodeError:
        candidate = extract_first_json_object(text)
        obj = json.loads(candidate)
        if not isinstance(obj, dict):
            raise ValueError("Recovered JSON is not a JSON object.")
        return obj


def extract_first_json_object(text: str) -> str:
    match = re.search(r"\{.*\}", text, flags=re.DOTALL)
    if not match:
        raise ValueError("Could not find JSON object in model output.")
    return match.group(0)


def quality_tag(match_score: int, capability_score: int) -> str:
    if match_score >= 5 and capability_score >= 5:
        return "strong_positive"
    if match_score >= 4 and capability_score >= 4:
        return "positive"
    if match_score >= 3 and capability_score >= 3:
        return "borderline"
    return "negative"


def keep_for_sft(match_score: int, capability_score: int) -> bool:
    return match_score >= 4 and capability_score >= 4


def generate_action_search(client: Any, query: str) -> dict[str, Any]:
    payload = {
        "query": query,
        "instruction": "Generate a search-oriented action prompt for an agentic controller."
    }
    result = client.json_completion(ACTION_SEARCH_SYSTEM_PROMPT, payload)
    required = ["action_search_prompt", "capability_keywords", "reasoning_type", "expected_evidence"]
    missing = [k for k in required if k not in result]
    if missing:
        raise ValueError(f"Action search output missing keys: {missing}")
    return result


def evaluate_trajectory(
    client: Any,
    query: str,
    gold_agent: dict[str, Any],
    action_search_prompt: str,
    session_history: list[dict[str, Any]],
    response_result: dict[str, Any],
) -> dict[str, Any]:
    payload = {
        "query": query,
        "gold_agent": gold_agent,
        "action_search_prompt": action_search_prompt,
        "session_history": session_history,
        "response_result": response_result,
    }
    result = client.json_completion(CRITIQUE_SYSTEM_PROMPT, payload)

    for key in ["match_score", "capability_score"]:
        if key not in result:
            raise ValueError(f"Critique output missing key: {key}")

    ms = int(result["match_score"])
    cs = int(result["capability_score"])
    result["match_score"] = max(1, min(6, ms))
    result["capability_score"] = max(1, min(6, cs))
    result["quality_tag"] = quality_tag(result["match_score"], result["capability_score"])
    result["keep_for_sft"] = keep_for_sft(result["match_score"], result["capability_score"])

    result.setdefault("match_rationale", "")
    result.setdefault("capability_rationale", "")
    result.setdefault("missing_capabilities", [])
    result.setdefault("noisy_or_irrelevant_components", [])
    return result


def build_record(input_payload: dict[str, Any], client: Any) -> SampleRecord:
    action = generate_action_search(client, input_payload["query"])
    run = input_payload["run"]

    eval_result = evaluate_trajectory(
        client=client,
        query=input_payload["query"],
        gold_agent=input_payload["gold_agent"],
        action_search_prompt=action["action_search_prompt"],
        session_history=run["session_history"],
        response_result=run["response_result"],
    )

    return SampleRecord(
        id=input_payload["id"],
        query=input_payload["query"],
        gold_agent=GoldAgent(**input_payload["gold_agent"]),
        action_search_prompt=action["action_search_prompt"],
        capability_keywords=action["capability_keywords"],
        reasoning_type=action["reasoning_type"],
        expected_evidence=action["expected_evidence"],
        run=RunArtifacts(**run),
        evaluation=Evaluation(**eval_result),
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Synthesize and evaluate agentic trajectories.")
    parser.add_argument("--input", required=True, help="Path to JSON file with query/gold_agent/run fields.")
    parser.add_argument("--output", required=True, help="Path to write final JSON sample.")
    parser.add_argument("--model", default=DEFAULT_MODEL, help="OpenAI model name.")
    parser.add_argument("--mock", action="store_true", help="Use mock model outputs for local testing.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    with open(args.input, "r", encoding="utf-8") as f:
        payload = json.load(f)

    client = MockClient() if args.mock else OpenAIResponsesClient(model=args.model)
    record = build_record(payload, client)

    with open(args.output, "w", encoding="utf-8") as f:
        json.dump(asdict(record), f, ensure_ascii=False, indent=2)
        f.write("\n")

    print(f"Wrote synthesized sample to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
